### ISSUE TITLE
Unable to compile - E0277, E0599

### ISSUE THREAD

**Issue by ghost** [odradev/odra#120]
I am unable to run the latest Odra 0.2.0, because of the following compilation errors:

```
error[E0277]: the trait bound `casper_hashing::Digest: ToBytes` is not satisfied
```

```
error[E0599]: no function or associated item named `from_bytes` found for struct `casper_hashing::Digest` in the current scope
```

Full build log (from clean state): [log.txt](https://github.com/odradev/odra/files/11522443/full_build_log.txt).

### Additional information

**Rust**:
- rustc 1.63.0-nightly (cacc75c82 2022-06-16)

**Toolchain** (based on [`rust-toolchain`](https://github.com/odradev/odra/blob/release/0.2.0/rust-toolchain)): 
- nightly-2022-06-17-x86_64-unknown-linux-gnu

**Comment by ghost** [comment]
Today I will send PR that updates all `casper-*` dependencies, as this resolves above mentioned errors.

**Comment by zie1ony** [comment]
CasperLabs didn't follow SemVer and introduced breaking changes where there should not.
Early next week we will release next Odra version that will work with `casper-types = 2.0.0` and `casper-execution-engine = 4.0.0`.
At the moment to use latest Odra you have to install `cargo-odra` using `feature/workspaces` branch. Then you'll be able to create new Odra project:
```bash
cargo odra new -n odra-evm -s release/0.2.1
```

I'll notify you here when `release/0.2.1` is released.

**Comment by zie1ony** [comment]
We have released Odra `release/0.3.0` and it plays well with Cargo Odra `release/0.0.7`. Please take a look and let us know. Closing, as this should work now. Please reopen if needed.

**Comment by ghost** [comment]
@zie1ony Thanks, it works now :smiley:
